// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nwhhulwpvvzuqzuqwoco.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im53aGh1bHdwdnZ6dXF6dXF3b2NvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzMzQ3OTgsImV4cCI6MjA2MTkxMDc5OH0.iHQbT3-RiYq8YiZU5P1zIKRy4rvzKcFAydUiBhjG7mo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);