// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bnhsyonejpdeozeqgiul.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJuaHN5b25lanBkZW96ZXFnaXVsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyNjg1NDksImV4cCI6MjA1OTg0NDU0OX0.fKnUWOz9VRXJILyb0HbFgcRc_DSitkvUnN9hvKf1OWA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);